In [1]:
import requests
import pandas as pd

url = "https://opendata.vancouver.ca/api/explore/v2.1/catalog/datasets/greenest-city-projects/records"

params = {"limit": 100, "offset": 0}
all_records = []

while True:
    response = requests.get(url, params=params)
    records = response.json().get("results", [])
    all_records.extend(records)
    if len(records) < 100:
        break
    params["offset"] += 100

greenest_city_projects = pd.DataFrame(all_records)
greenest_city_projects.to_csv("greenest_city_projects.csv", index=False)

In [2]:
import requests
import pandas as pd

url = "https://opendata.vancouver.ca/api/explore/v2.1/catalog/datasets/community-gardens-and-food-trees/records"

params = {"limit": 100, "offset": 0}
all_records = []

while True:
    response = requests.get(url, params=params)
    records = response.json().get("results", [])
    all_records.extend(records)
    if len(records) < 100:
        break
    params["offset"] += 100

community_gardens = pd.DataFrame(all_records)
community_gardens.to_csv("community_gardens.csv", index=False)

In [3]:
import requests

url = "https://opendata.vancouver.ca/api/explore/v2.1/catalog/datasets/local-area-boundary/exports/geojson"

response = requests.get(url)

with open("vancouver_neighbourhoods.geojson", "wb") as f:
    f.write(response.content)

In [4]:
greenest_city_projects.head(5)

,mapid,name,category1,category2,address,short_description,url,url2,url3,geom,geo_local_area
0,GCP002,Southeast False Creek Neighbourhood Ener,City projects,Climate-Leadership,None,City's first neighbourhood energy system servi...,http://vancouver.ca/home-property-development/...,None,http://www.greenbuildingaudiotours.com/buildin...,"{'type': 'Feature', 'geometry': {'coordinates'...",Mount Pleasant
1,GCP008,LEED Platinum Building Certified in 2010,City projects,Green-Buildings,51 W 1st AV,City of Vancouver Housing - Net Zero Building ...,http://www.thechallengeseries.ca/chapter-07/ne...,None,None,"{'type': 'Feature', 'geometry': {'coordinates'...",Mount Pleasant
2,GCP019,LEED Gold for Commercial Interiors 2011,Private projects,Green-Buildings,507 W Broadway,City of Vancouver Engineering Services,http://edgesustainability.com/?portfolio=city-...,None,None,"{'type': 'Feature', 'geometry': {'coordinates'...",Fairview
3,GCP023,LEED Gold Building Certified 2010,Private projects,Green-Buildings,199 W 1st AV,SEFC Parcel 2 (Millennium Water / City of Vanc...,http://www.millenniumdevelopment.com/Olympic-V...,None,http://www.gbig.org/activities/cagbc-10522,"{'type': 'Feature', 'geometry': {'coordinates'...",Mount Pleasant
4,GCP041,City Studio,City Studio Project,Lighter-Footprint,1800 Spyglass Place,A multi-disciplinary applied program for post-...,http://citystudiovancouver.com/,None,None,"{'type': 'Feature', 'geometry': {'coordinates'...",Fairview

In [5]:
import ast

greenest_city_projects = pd.read_csv("greenest_city_projects.csv")

def parse_coords_gcp(geom_str):
    try:
        geom = ast.literal_eval(geom_str)
        coords = geom["geometry"]["coordinates"]
        return pd.Series({"longitude": coords[0], "latitude": coords[1]})
    except:
        return pd.Series({"longitude": None, "latitude": None})

greenest_city_projects[["longitude", "latitude"]] = greenest_city_projects["geom"].apply(parse_coords_gcp)
greenest_city_projects.to_csv("greenest_city_projects.csv", index=False)

In [6]:
greenest_city_projects.head()

,mapid,name,category1,category2,address,short_description,url,url2,url3,geom,geo_local_area,longitude,latitude
0,GCP002,Southeast False Creek Neighbourhood Ener,City projects,Climate-Leadership,NaN,City's first neighbourhood energy system servi...,http://vancouver.ca/home-property-development/...,NaN,http://www.greenbuildingaudiotours.com/buildin...,"{'type': 'Feature', 'geometry': {'coordinates'...",Mount Pleasant,-123.114480,49.267175
1,GCP008,LEED Platinum Building Certified in 2010,City projects,Green-Buildings,51 W 1st AV,City of Vancouver Housing - Net Zero Building ...,http://www.thechallengeseries.ca/chapter-07/ne...,NaN,NaN,"{'type': 'Feature', 'geometry': {'coordinates'...",Mount Pleasant,-123.104673,49.270203
2,GCP019,LEED Gold for Commercial Interiors 2011,Private projects,Green-Buildings,507 W Broadway,City of Vancouver Engineering Services,http://edgesustainability.com/?portfolio=city-...,NaN,NaN,"{'type': 'Feature', 'geometry': {'coordinates'...",Fairview,-123.115417,49.263366
3,GCP023,LEED Gold Building Certified 2010,Private projects,Green-Buildings,199 W 1st AV,SEFC Parcel 2 (Millennium Water / City of Vanc...,http://www.millenniumdevelopment.com/Olympic-V...,NaN,http://www.gbig.org/activities/cagbc-10522,"{'type': 'Feature', 'geometry': {'coordinates'...",Mount Pleasant,-123.101856,49.270148
4,GCP041,City Studio,City Studio Project,Lighter-Footprint,1800 Spyglass Place,A multi-disciplinary applied program for post-...,http://citystudiovancouver.com/,NaN,NaN,"{'type': 'Feature', 'geometry': {'coordinates'...",Fairview,-123.115323,49.270547

In [7]:
greenest_city_projects["category2"].value_counts()

category2
Local-Food                   173
Clean-Air                     33
Lighter-Footprint             30
Green-Buildings               25
Access-to-Nature              24
Zero-Waste                    17
Green-Transportation          13
Green-Economy                  5
Climate-Leadership             3
Green-BuildingsLocal-Food      1
Name: count, dtype: int64

In [8]:
greenest_city_projects["address"] = greenest_city_projects["address"].fillna("Address not specified")
greenest_city_projects.to_csv("greenest_city_projects.csv", index=False)

In [9]:
greenest_city_projects.head()

,mapid,name,category1,category2,address,short_description,url,url2,url3,geom,geo_local_area,longitude,latitude
0,GCP002,Southeast False Creek Neighbourhood Ener,City projects,Climate-Leadership,Address not specified,City's first neighbourhood energy system servi...,http://vancouver.ca/home-property-development/...,NaN,http://www.greenbuildingaudiotours.com/buildin...,"{'type': 'Feature', 'geometry': {'coordinates'...",Mount Pleasant,-123.114480,49.267175
1,GCP008,LEED Platinum Building Certified in 2010,City projects,Green-Buildings,51 W 1st AV,City of Vancouver Housing - Net Zero Building ...,http://www.thechallengeseries.ca/chapter-07/ne...,NaN,NaN,"{'type': 'Feature', 'geometry': {'coordinates'...",Mount Pleasant,-123.104673,49.270203
2,GCP019,LEED Gold for Commercial Interiors 2011,Private projects,Green-Buildings,507 W Broadway,City of Vancouver Engineering Services,http://edgesustainability.com/?portfolio=city-...,NaN,NaN,"{'type': 'Feature', 'geometry': {'coordinates'...",Fairview,-123.115417,49.263366
3,GCP023,LEED Gold Building Certified 2010,Private projects,Green-Buildings,199 W 1st AV,SEFC Parcel 2 (Millennium Water / City of Vanc...,http://www.millenniumdevelopment.com/Olympic-V...,NaN,http://www.gbig.org/activities/cagbc-10522,"{'type': 'Feature', 'geometry': {'coordinates'...",Mount Pleasant,-123.101856,49.270148
4,GCP041,City Studio,City Studio Project,Lighter-Footprint,1800 Spyglass Place,A multi-disciplinary applied program for post-...,http://citystudiovancouver.com/,NaN,NaN,"{'type': 'Feature', 'geometry': {'coordinates'...",Fairview,-123.115323,49.270547

In [10]:
greenest_city_projects = greenest_city_projects.drop(columns=["url2","url3"])

In [11]:
greenest_city_projects.to_csv("greenest_city_projects.csv", index=False)

In [12]:
greenest_city_projects.head()

,mapid,name,category1,category2,address,short_description,url,geom,geo_local_area,longitude,latitude
0,GCP002,Southeast False Creek Neighbourhood Ener,City projects,Climate-Leadership,Address not specified,City's first neighbourhood energy system servi...,http://vancouver.ca/home-property-development/...,"{'type': 'Feature', 'geometry': {'coordinates'...",Mount Pleasant,-123.114480,49.267175
1,GCP008,LEED Platinum Building Certified in 2010,City projects,Green-Buildings,51 W 1st AV,City of Vancouver Housing - Net Zero Building ...,http://www.thechallengeseries.ca/chapter-07/ne...,"{'type': 'Feature', 'geometry': {'coordinates'...",Mount Pleasant,-123.104673,49.270203
2,GCP019,LEED Gold for Commercial Interiors 2011,Private projects,Green-Buildings,507 W Broadway,City of Vancouver Engineering Services,http://edgesustainability.com/?portfolio=city-...,"{'type': 'Feature', 'geometry': {'coordinates'...",Fairview,-123.115417,49.263366
3,GCP023,LEED Gold Building Certified 2010,Private projects,Green-Buildings,199 W 1st AV,SEFC Parcel 2 (Millennium Water / City of Vanc...,http://www.millenniumdevelopment.com/Olympic-V...,"{'type': 'Feature', 'geometry': {'coordinates'...",Mount Pleasant,-123.101856,49.270148
4,GCP041,City Studio,City Studio Project,Lighter-Footprint,1800 Spyglass Place,A multi-disciplinary applied program for post-...,http://citystudiovancouver.com/,"{'type': 'Feature', 'geometry': {'coordinates'...",Fairview,-123.115323,49.270547

In [13]:
greenest_city_projects[greenest_city_projects["geo_local_area"].isna()]

,mapid,name,category1,category2,address,short_description,url,geom,geo_local_area,longitude,latitude
38,GCP307,Community Garden,Private projects,Local-Food,1025 Boundary Rd,Adanac Park,http://vancouver.ca/people-programs/community-...,"{'type': 'Feature', 'geometry': {'coordinates'...",NaN,-123.022970,49.277597
117,GCP012,LEED Gold Building Certified 2012,Private projects,Green-Buildings,1866 Main Mall,UBC Renew - Buchanan Complex,http://www.projectservices.lbs.ubc.ca/portfoli...,"{'type': 'Feature', 'geometry': {'coordinates'...",NaN,-123.254882,49.267303
129,GCP268,Electric Vehicle Charging Station,Private projects,Clean-Air,3228 Ross Drive,U-Hill Sec. 2 charging stations are available ...,http://www.plugshare.com/?location=14875,"{'type': 'Feature', 'geometry': {'coordinates'...",NaN,-123.240176,49.253905
150,GCP102,Stanley Park Ecology Society,Greenest City Fund Project,Access-to-Nature,Stanley Park,2012 Greenest City Community grant fund projec...,http://vancouver.ca/news-calendar/city-and-van...,"{'type': 'Feature', 'geometry': {'coordinates'...",NaN,-123.137587,49.294498
269,GCP018,LEED Gold Building Certified 2011,Private projects,Green-Buildings,2177 Wbrook Mall,UBC Renew Friedman Building,http://recollective.ca/projects/ubc-friedman-b...,"{'type': 'Feature', 'geometry': {'coordinates'...",NaN,-123.246072,49.265360
310,GCP267,Electric Vehicle Charging Station,Private projects,Clean-Air,6085 Thunderbird Boulevard,Thunderbird Parkade. 8 Public Stations,http://www.plugshare.com/?location=14212,"{'type': 'Feature', 'geometry': {'coordinates'...",NaN,-123.244531,49.260675
311,GCP269,Electric Vehicle Charging Station,Private projects,Clean-Air,4250 Wesbrook Mall,National Research Council Canada. For NRC visi...,http://www.plugshare.com/?location=15536,"{'type': 'Feature', 'geometry': {'coordinates'...",NaN,-123.232428,49.245308

In [14]:
greenest_city_projects.loc[greenest_city_projects["geo_local_area"].isna(), "geo_local_area"] = greenest_city_projects.loc[greenest_city_projects["geo_local_area"].isna()].apply(
    lambda row: (
        "Brentwood" if "Adanac" in str(row["short_description"])
        else "Stanley Park" if row["address"].strip() == "Stanley Park"
        else "University of British Columbia"
    ),
    axis=1
)

In [15]:
greenest_city_projects.to_csv("/Users/camillascandola/Desktop/vancity-greenest-city/greenest_city_projects.csv", index=False)

In [16]:
greenest_city_projects["geo_local_area"].value_counts()["Brentwood"]

np.int64(1)